In [1]:
import __init__

[INFO] adding /Users/apple/Documents/GitHub/batch4_diafoirus_fleming to sys.path

In [2]:
import numpy as np
import pandas as pd
import datetime

# Open a connection to OMOP
from fleming_lib.tools import connect_to_omop
conn = connect_to_omop()

In [12]:
query = """
select 
    *
from
    concept
where
    
    domain_id = 'Unit'
    ;"""

search = pd.read_sql_query(query, conn)
search

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
0,2000000001,L/min/m2,Unit,None,None,None,MIMIC Generated,1979-01-01,2099-01-01,None
1,2000000002,dynes.sec.cm-5/m2,Unit,None,None,None,MIMIC Generated,1979-01-01,2099-01-01,None
2,4310862,ng/hr,Unit,SNOMED,Qualifier Value,None,422398009,1970-01-01,2099-12-31,None
3,4112118,/hour,Unit,SNOMED,Qualifier Value,None,286551008,1970-01-01,2099-12-31,None
4,4245713,m3/sec,Unit,SNOMED,Qualifier Value,None,396170008,1970-01-01,2099-12-31,None
5,9546,meter,Unit,UCUM,Unit,S,m,1970-01-01,2099-12-31,None
6,9376,pica,Unit,UCUM,Unit,S,[pca],1970-01-01,2099-12-31,None
7,8505,hour,Unit,UCUM,Unit,S,h,1970-01-01,2099-12-31,None
8,4223755,Imperial gallon,Unit,SNOMED,Qualifier Value,None,422049005,1970-01-01,2099-12-31,None
9,4208468,Drops per minute,Unit,SNOMED,Qualifier Value,None,439139003,2009-01-31,2099-12-31,None
10,4169432,% index,Unit,SNOMED,Qualifier Value,None,419205000,1970-01-01,2099-12-31,None
11,4123537,% energy intake,Unit,SNOMED,Qualifier Value,None,288493004,1970-01-01,2099-12-31,None
12,4120714,% normal forms,Unit,SNOMED,Qualifier Value,None,258749005,1970-01-01,2099-12-31,None
13,4120715,% of total,Unit,SNOMED,Qualifier Value,None,258755000,1970-01-01,2099-12-31,None
14,4120716,% positive cells,Unit,SNOMED,Qualifier Value,None,258758003,1970-01-01,2099-12-31,None
15,4120717,% release,Unit,SNOMED,Qualifier Value,None,258760001,1970-01-01,2099-12-31,None
16,4120718,Unit of volume,Unit,SNOMED,Qualifier Value,None,258769000,1970-01-01,2099-12-31,None
17,4120719,microlitre,Unit,SNOMED,Qualifier Value,None,258774008,1970-01-01,2099-12-31,None
18,4120720,nkat,Unit,SNOMED,Qualifier Value,None,258780000,1970-01-01,2099-12-31,None
19,4120721,J,Unit,SNOMED,Qualifier Value,None,258786006,1970-01-01,2099-12-31,None
20,4120722,g/l,Unit,SNOMED,Qualifier Value,None,258794004,1970-01-01,2099-12-31,None
21,4120723,ng/L,Unit,SNOMED,Qualifier Value,None,258804004,1970-01-01,2099-12-31,None
22,4120724,nanogram/ml,Unit,SNOMED,Qualifier Value,None,258806002,1970-01-01,2099-12-31,None
23,4118133,IU/L,Unit,SNOMED,Qualifier Value,None,259001000,1970-01-01,2099-12-31,None
24,4118134,IU/day,Unit,SNOMED,Qualifier Value,None,259008006,1970-01-01,2099-12-31,None
25,4117808,casts/uL,Unit,SNOMED,Qualifier Value,None,258876001,1970-01-01,2099-12-31,None
26,4117809,fg/platelet,Unit,SNOMED,Qualifier Value,None,258888004,1970-01-01,2099-12-31,None
27,4117810,fmol/macrophage,Unit,SNOMED,Qualifier Value,None,258890003,1970-01-01,2099-12-31,None
28,4117811,gram nitrogen/day,Unit,SNOMED,Qualifier Value,None,258894007,1970-01-01,2099-12-31,None
29,4117812,g/kL,Unit,SNOMED,Qualifier Value,None,258895008,1970-01-01,2099-12-31,None
...,...,...,...,...,...,...,...,...,...,...
2249,45757020,blister,Unit,SNOMED,Qualifier Value,None,3320911000001100,1970-01-01,2008-10-31,U
2250,45757021,bar,Unit,SNOMED,Qualifier Value,None,3321211000001103,1970-01-01,2008-10-31,U
2251,45757022,dual dose sachet,Unit,SNOMED,Qualifier Value,None,3314111000001100,1970-01-01,2008-10-31,U
2252,45757023,g/actuation,Unit,SNOMED,Qualifier Value,None,3989311000001105,1970-01-01,2007-09-30,U
2253,45757024,unit/actuation,Unit,SNOMED,Qualifier Value,None,3989211000001102,1970-01-01,2007-09-30,U
2254,45757025,micrograms/square cm,Unit,SNOMED,Qualifier Value,None,3990011000001103,1970-01-01,2008-10-31,U
2255,45757026,kit,Unit,SNOMED,Qualifier Value,None,4027211000001105,1970-01-01,2008-10-31,U
2256,45757027,component,Unit,SNOMED,Qualifier Value,None,10204911000001107,1970-01-01,2006-06-05,U
2257,45757028,micromol/ml,Unit,SNOMED,Qualifier Value,None,8082911000001107,1970-01-01,2007-09-30,U
2258,45757029,microlitre/ml,Unit,SNOMED,Qualifier Value,None,8083011000001104,1970-01-01,2008-10-31,U
2259,45757030,nanolitre/ml,Unit,SNOMED,Qualifier Value,None,8083111000001103,1970-01-01,2008-10-31,U
2260,45757031,unit/square cm,Unit,SNOMED,Qualifier Value,None,8083611000001106,1970-01-01,2008-10-31,U
2261,45757032,can,Unit,SNOMED,Qualifier Value,None,8083911000001100,1970-01-01,2008-10-31,U
2262,45757033,ml/gram,Unit,SNOMED,Qualifier Value,None,8088611000001104,1970-01-01,2008-10-31,U
2263,45757034,GBq,Unit,SNOMED,Qualifier Value,None,8090611000001103,1970-01-01,2008-10-31,U
2264,45757035,GBq/ml,Unit,SNOMED,Qualifier Value,None,8090711000001107,1970-01-01,2007-09-30,U
2265,45757036,MBq/ml,Unit,SNOMED,Qualifier Value,None,8090911000001109,1970-01-01,2008-10-31,U
2266,45757037,mol/l,Unit,SNOMED,Qualifier Value,None,10368311000001109,1970-01-01,2007-09-30,U
2267,45757038,cup,Unit,SNOMED,Qualifier Value,None,11005411000001103,1970-01-01,2008-10-31,U
2268,45756995,mg/16 hours,Unit,SNOMED,Qualifier Value,None,3315211000001107,1970-01-01,2007-09-30,U
2269,45756996,mg/72 hours,Unit,SNOMED,Qualifier Value,None,3315311000001104,1970-01-01,2007-09-30,U
2270,45756997,mg/g,Unit,SNOMED,Qualifier Value,None,3315411000001106,1970-01-01,2007-09-30,U
2271,45756998,mg/kg,Unit,SNOMED,Qualifier Value,None,3315511000001105,1970-01-01,2007-09-30,U
2272,46274038,Red blood cells per high power field,Unit,SNOMED,Qualifier Value,None,1991000175108,2015-07-31,2099-12-31,None
2273,46270335,Lymphs/uL,Unit,SNOMED,Qualifier Value,None,1981000175105,2015-07-31,2099-12-31,None
2274,46270336,Thousand unit,Unit,SNOMED,Qualifier Value,None,2011000175108,2015-07-31,2099-12-31,None
2275,46270346,Ten unit,Unit,SNOMED,Qualifier Value,None,2671000175107,2015-07-31,2099-12-31,None
2276,46270463,times/morning,Unit,SNOMED,Qualifier Value,None,3081000175107,2015-07-31,2099-12-31,None
2277,46273486,White blood cells per high power field,Unit,SNOMED,Qualifier Value,None,2001000175105,2015-07-31,2099-12-31,None
2278,9693,index of reactivity,Unit,UCUM,Unit,S,{ir},2014-12-01,2099-12-31,None